services:
  app-ctl:
    build:
      context: ./app-ctl
      dockerfile: Dockerfile.dev
    ports:
      - "50001:8080"
    volumes:
      - ./app-ctl:/go/src
    working_dir: /go/src
    command: air
    depends_on:
      - redis
    env_file:
      - endpoints.env

  app-redirect:
    build:
      context: ./app-redirect
      dockerfile: Dockerfile.dev
    ports:
      - "50002:8080"
    volumes:
      - ./app-redirect:/go/src
    working_dir: /go/src
    command: air
    depends_on:
      - redis
    env_file:
      - endpoints.env

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always

volumes:
  redis-data:
