services:
  app-ctl:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src
    working_dir: /go/src
    command: air
    depends_on:
      - redis
    env_file:
      - config.env

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always

volumes:
  redis-data:
